<?php

use Drupal\Core\Url;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implementing hook_theme().
 */
function vf_reservation_theme($existing, $type, $theme, $path)
{
  return [
    'reservation' => [
      'render element' => 'content',
      'variables' => [
        'user_mobile' => null,
        'categories' => [],
      ],
    ],
    'suggestions' => [
      'render element' => 'content',
      'variables' => [
        'suggtions' => null,
      ],
    ],
    'stores' => [
      'render element' => 'content',
      'variables' => [
        'data' => null,
      ],
    ],
  ];
}

/**
 * Implementing hook_page_attachments_alter().
 */
function vf_reservation_page_attachments_alter(&$page)
{
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === "vf_reservation.home") {
    $page['#attached']['library'][] = 'vf_reservation/vf_reservation';
  }
}

function vf_reservation_preprocess_views_view_field(&$vars)
{
  if (isset($vars['view']) && ($vars['view']->id() == 'stores')) {
    if ($vars['field']->field == 'nothing') {
      $number = \Drupal::request()->request->get('mobile') ?? '-';
      $problem = \Drupal::request()->request->get('problem') ?? '-';
      $category = \Drupal::request()->request->get('category') ?? '-';
      $store = $vars['row']->nid;
      $out = $vars['output']->__toString();
      $out = str_replace('/reserve', "/reserve?st=" . $store . "&mn=" . $number . "&" . "prob=" . $problem . "&" . "cat=" . $category, $out);
      $vars['output'] = (new \Drupal\Core\Render\Markup())->create($out);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function vf_reservation_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  if ($form_id == 'node_reservation_form') {
    $store = \Drupal::request()->get('st');
    $storeNode = \Drupal\node\Entity\Node::load($store);
    if ($storeNode) {
      $mobile = \Drupal::request()->get('mn');
      $problem = \Drupal::request()->get('prob');
      $category = \Drupal::request()->get('cat');

      $createdRevision = \Drupal::entityQuery('node')
        ->condition('type', 'reservation')
        ->condition('field_reservation_user', \Drupal::currentUser()->id())
        ->condition('field_reservation_status', "waiting in the queue")
        ->execute();
      if (!empty($createdRevision)) {
        \Drupal::messenger()->addWarning("you have a reservation already!");
        $redirect = new \Symfony\Component\HttpFoundation\RedirectResponse("/reservations");
        $redirect->send();
        return;
      }

      $problemNode = \Drupal\node\Entity\Node::create([
        'type' => 'problems',
        'title' => $problem,
        'field_category' => $category
      ]);
      $problemNode->save();

      $uid = \Drupal::currentUser()->id();
      // title is the reservation id

      $reservationID = "#" . str_replace(' ', '-', $storeNode->label()) . "-" . rand(1, 10000000000) * 1000;
      $form['title']['widget'][0]['value']['#default_value'] = $reservationID;
      $form['field_phone_number']['widget'][0]['value']['#default_value'] = $mobile;
      $form['field_reservation_problem']['widget'][0]['target_id']['#default_value'] = $problemNode;
      $form['field_reservation_store']['widget'][0]['target_id']['#default_value'] = $storeNode;
      $form['field_reservation_problem']['#disabled'] = TRUE;
      $form['field_reservation_store']['#disabled'] = TRUE;
      $form['title']['#disabled'] = TRUE;
      unset($form['actions']['preview']);
      $form['actions']['submit']['#value'] = t("Reserve at the store");
    } else {
      \Drupal::messenger()->addError("something went wrong!");
    }
    $form_state->setRedirectUrl(new \Drupal\Core\Url('/reservations'));
  }
}

/**
 * Implements hook_entity_presave().
 */
function vf_reservation_entity_presave(\Drupal\Core\Entity\EntityInterface $entity)
{

  if ($entity->bundle() == 'reservation') {
    $entity->field_reservation_user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $entity->field_reservation_user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $currentReservation = $entity->field_reservation_status->value;
    if (!isset($currentReservation)) {
      $entity->field_reservation_status = "waiting in the queue";
    }

    // set the reservation id

    if (!isset($entity->field_reservation_queue_number->value)) {
      // check if the store has a reservation number
      $store = \Drupal\node\Entity\Node::load($entity->field_reservation_store->getString());
      $currentInQueue = intval($store->get('field_currently_served_customer')->getString());
      if ($currentInQueue || $currentInQueue == 0) {
        // get from reservations

        $connection = \Drupal::database();

        $biggestReservationValue = intval($connection->query("SELECT MAX(nd.field_reservation_queue_number_value) AS mxValue
            FROM `node_revision__field_reservation_queue_number` AS nd
            JOIN node_field_data fd ON fd.nid = nd.entity_id
            JOIN node_revision__field_reservation_store st on st.entity_id = nd.entity_id
            WHERE DATE(FROM_UNIXTIME(fd.created)) = CURRENT_DATE
            AND st.field_reservation_store_target_id =" . $store->id())->fetchAll()[0]->mxValue);
        $entity->field_reservation_queue_number = $biggestReservationValue + 1;
        $peopleInQueue = intval($store->get('field_number_of_people_in_queue')->getString());
        $store->set('field_number_of_people_in_queue', $peopleInQueue + 1);
        $entity->field_estimated_waittime = $peopleInQueue * intval($store->get('field_average_waiting_time')->getString());
      } else {
        $entity->field_reservation_queue_number = 1;
        $store->set('field_number_of_people_in_queue', 1);
      }
      $store->save();
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function vf_reservation_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity)
{
  $entityTypeId = $entity->getEntityTypeId();
  if ($entityTypeId !== 'node') {
    return;
  }
  $nodeType = $entity->getType();
  $nodeId = $entity->id();
  if ($nodeType === 'reservation') {

    $currentReservation = $entity->field_reservation_status->value;
    if ($currentReservation == 'waiting in the queue') {
      if (in_array('store_agent', \Drupal::currentUser()->getRoles())) {
        $assignUrl = Url::fromRoute('vf_reservation.assign_to_me',
          ['rid' => $nodeId,
            'uid' => \Drupal::currentUser()->id()]
        );
        $operations['assign_to_me'] = array(
          'title' => t('Assign to me'),
          'weight' => 20,
          'url' => $assignUrl,
        );
      }
    }
    if ($currentReservation == 'being served') {
      if (in_array('store_agent', \Drupal::currentUser()->getRoles())) {
        $resolveUrl = Url::fromRoute('vf_reservation.resolve',
          ['rid' => $nodeId]
        );
        $operations['problem_solved'] = array(
          'title' => t('Resolve'),
          'weight' => 20,
          'url' => $resolveUrl,
        );
      }

    }

  }
}
